apiVersion: v1
kind: PersistentVolumeClaim


metadata:
  name: mysql-pvc

spec:
  storageClassName: my-storage
  accessModes:
    - ReadWriteOnce
  resources: # pv -> pvc에게 요청하는 용량의 양
    requests:
      storage: 1Gi