apiVersion: v1
kind: Service

metadata:
  name: spring-service

# Service의 상세정보
spec:
#  type: ClusterIP # 내부에서만 통신할 수 있게함
#  type: LoadBalancer # 외부의 로드밸런서(AWS의 로드밸런서 등)를 활용해 외부에서 접속할 수 있도록 함
  type: NodePort # 외부에서 접속가능하도록 함
  selector:
    app: backend-app # 어떤 파드에 연결할 것인지
  ports: # 서비스는 독립적인 Pod로 접근할수 있도록함
    - protocol: TCP
      port: 8080 # 쿠버네티스 내부에서 Service에 접속하기 위한 포트
      targetPort: 8080 # 어떤 port로 연결을 시킬것 인지
      nodePort: 30000 # 외부에서 사용자들이 접근하게 될 포트

